# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
require "bundler"
Bundler.require(:default, :development)

require "savon/mock/spec_helper"

if ENV['COVERAGE']
  require 'simplecov'
  SimpleCov.start
else
  require 'coveralls'
  Coveralls.wear!
end

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
  config.mock_with :rspec 
end

def f method, response
  File.read File.join(File.expand_path("../fixtures", __FILE__), method.to_s, "#{response.to_s}.xml")
end

require 'profitbricks'

HTTPI.log = false

Profitbricks.configure do |config|
  config.username = "none"
  config.password = "none"
  config.polling_interval = 0.1 
end


require "httpi"

# FIXME trying to debug travis-ci build issues
module Wasabi
  class Resolver
    private
    def load_from_remote
      request.url = document
      response = HTTPI.get(request)
      puts response.body
      raise HTTPError.new("Error: #{response.code}", response) if response.error?

      response.body
    end
  end
end
